### ISSUE TITLE
Agregar Registro.

### ISSUE THREAD

**Issue by ah-kodeit** [kodeitsolutions/kfmakes#17]
El botón cancelar del formulario "Agregar Registro" debe :
- Preguntar si se esta seguro de cancelar la creacion de un registro.
- Ir directamete a la lista del registro del log del día, si es presionado el boton cancelar luego de haber presionado el boton aceptar, se muestra nuevamente el formulario de Agregar Registro.

**Comment by ah-kodeit** [comment]
¿Marcamos esto como listo?

**Comment by gs-kodeit** [comment]
Hola. Sí, recuerda que este fue el que dije que lo habías agregado donde no
era. Es de ReMo y lo pusiste en KFMakes.

**Comment by ah-kodeit** [comment]
OK! Cierto.
